# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JR-Project CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#  test-container:
#    runs-on: ubuntu-latest
#    container: ubuntu
#    services:
#      test-rprj-mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_ROOT_PASSWORD: mysecret
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
#    steps:
#      - uses: actions/checkout@v2
#      - name: Verify MySQL connection from container
#        run: |
#          apt-get update
#          apt-get install -y mysql-client
#          mysql --host test-rprj-mysql -uroot -pmysecret < ./sql/db_rproject.sql
#          mysql --host test-rprj-mysql -uroot -pmysecret -e "SHOW DATABASES"
#          mysql --host test-rprj-mysql -uroot -pmysecret rproject -e "SHOW TABLES"

#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up JDK 1.11
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.11
#    - name: Build with Maven
#      run: mvn -B package -Dmaven.test.skip=true --file pom.xml

  test:
    runs-on: ubuntu-latest
    services:
      java-rprj-mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: mysecret
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - uses: actions/checkout@v2
    - name: Setup Database
      run: |
        mysql --host 127.0.0.1 -uroot -pmysecret < ./sql/db_test.sql
        mysql --host 127.0.0.1 -uroot -pmysecret rproject -e "SHOW TABLES"
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B test --file pom.xml

  test-maria:
    runs-on: ubuntu-latest
    services:
      java-rprj-maria:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: mysecret
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Database
        run: |
          mysql --host 127.0.0.1 -uroot -pmysecret < ./sql/db_test.sql
          mysql --host 127.0.0.1 -uroot -pmysecret rproject -e "SHOW TABLES"
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -B test --file pom.xml
