# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-container:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      java-rprj-mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: mysecret
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Verify MySQL connection from container
        run: |
          apt-get update
          apt-get install -y mysql-client
          mysql --host java-rprj-mysql -uroot -ppassword -e "SHOW DATABASES"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml
